# Generated by Django 2.0 on 2018-03-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_book_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
