# Generated by Django 2.0 on 2018-03-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_auto_20180307_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='writer_img',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
